source 'https://rubygems.org'

ruby '2.4.2'

gem 'activesupport'
gem 'cassandra-driver'
gem 'faraday'
gem 'faraday_middleware'
gem 'mongo'
gem 'multi_json'
gem 'rainbow'
gem 'ruby-kafka'
gem 'thor'
gem 'xa-rules', git: 'https://github.com/Xalgorithms/xa-rules.git'
gem 'xa-ubl', git: 'https://github.com/Xalgorithms/xa-ubl.git'

group :development do
  gem 'pry'
end
